apiVersion: v1
kind: Service
metadata:
  name: orderbird-service
  namespace: orderbird
spec:
  selector:
    app: orderbird
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
